import "@/app/assets/styles/globals.css";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = await createSupabaseServerClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="flex items-center justify-between border-b px-6 py-3">
          <h1 className="font-semibold">Task Manager</h1>

          <div className="flex items-center gap-4">
            <span className="text-sm">
              {user?.user_metadata?.name ?? user?.email}
            </span>

            <form action="/auth/logout" method="post">
              <button className="text-sm underline">Logout</button>
            </form>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
